plugins = [
  "/home/dave/Workspace/davebrent/hans/src/plugins/gfx-attractors",
  "/home/dave/Workspace/davebrent/hans/src/plugins/gfx-displace",
  "/home/dave/Workspace/davebrent/hans/src/plugins/gfx-filter",
  "/home/dave/Workspace/davebrent/hans/src/plugins/gfx-image",
  "/home/dave/Workspace/davebrent/hans/src/plugins/gfx-noise",
  "/home/dave/Workspace/davebrent/hans/src/plugins/gfx-quad",
  "/home/dave/Workspace/davebrent/hans/src/plugins/gfx-scopes",
  "/home/dave/Workspace/davebrent/hans/src/plugins/gfx-sndtex",
  "/home/dave/Workspace/davebrent/hans/src/plugins/gfx-superformula",
  "/home/dave/Workspace/davebrent/hans/src/plugins/gfx-video",
  "/home/dave/Workspace/davebrent/hans/src/plugins/snd-analysis",
  "/home/dave/Workspace/davebrent/hans/src/plugins/snd-io",
  "/home/dave/Workspace/davebrent/hans/src/plugins/snd-oscillator",
  "/home/dave/Workspace/davebrent/hans/src/plugins/snd-ringbuffer",
]

[reload]
delay = 3
extensions = [".toml", ".so", ".a", ".dylib"]
paths = ["/home/dave/Workspace/davebrent/hans"]
exclude = ["/home/dave/Workspace/davebrent/hans/.git"]

# Global settings

[settings]
[settings.graphics]
width = 720
height = 405
[settings.audio]
backend = "jack"
input_device = "default"
output_device = "default"
samplerate = 48000
blocksize = 128
input_channels = [0, 1]
output_channels = [0, 1]

# Images

[[programs]]
name = "images"
[programs.objects]
image  = { object = "gfx-image", args = [ { filepath = "/home/dave/Workspace/davebrent/hans-assets/dist/01.webp" },
                                          { filepath = "/home/dave/Workspace/davebrent/hans-assets/dist/02.webp" },
                                          { filepath = "/home/dave/Workspace/davebrent/hans-assets/dist/03.webp" },
                                          { filepath = "/home/dave/Workspace/davebrent/hans-assets/dist/04.webp" },
                                          { filepath = "/home/dave/Workspace/davebrent/hans-assets/dist/07.webp" },
                                          { filepath = "/home/dave/Workspace/davebrent/hans-assets/dist/08.webp" },
                                          { filepath = "/home/dave/Workspace/davebrent/hans-assets/dist/09.webp" },
                                          { filepath = "/home/dave/Workspace/davebrent/hans-assets/dist/10.webp" },
                                          { filepath = "/home/dave/Workspace/davebrent/hans-assets/dist/12.webp" } ] }
effect = { object = "gfx-filter" }
effect2 = { object = "gfx-filter" }
window = { object = "gfx-quad" }
[[programs.graphics]]
source = "image"
outlet = 0
sink   = "effect"
inlet  = 0
[[programs.graphics]]
source = "effect"
outlet = 0
sink   = "effect2"
inlet  = 0
[[programs.graphics]]
source = "effect2"
outlet = 0
sink   = "window"
inlet  = 0

# 0 PASSTHROUGH
# 1 PIXELATE
# 2 GREYSCALE
# 3 INVERT
# 4 RGB2YUV
# 5 RGBSPLIT
# 6 BARRELDISTORT
# 7 GAUSBLUR
# 8 HORIZONTAL_CLAMP
# 9 VERTICAL_CLAMP

[[programs.tracks]]
sequence = "10000 dur [ 0 1 2 3 [ 4 7 ] 8 9 [ 10 11 ] ]"
target   = { object = "image", parameter = "image", component = 0 }
[[programs.tracks]]
sequence = "10000 dur [ 8 2 0 7 9 0 5 0 ]"
target   = { object = "effect", parameter = "filter", component = 0 }
[[programs.tracks]]
sequence = "500 dur [ 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 1 0.2 0.3 0.4 0.6 0.9 10 20 30 40 60 40 50 ] palindrome"
target   = { object = "effect", parameter = "amount", component = 0 }
[[programs.tracks]]
sequence = "500 dur [ 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1 ]"
target   = { object = "effect", parameter = "amount", component = 1 }
[[programs.tracks]]
sequence = "20000 dur [ 0 1 5 2 ]"
target   = { object = "effect2", parameter = "filter", component = 0 }
[[programs.tracks]]
sequence = "1000 dur [ 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 1 0.2 0.3 0.4 0.6 0.9 10 20 30 40 60 40 50 ] palindrome"
target   = { object = "effect2", parameter = "amount", component = 0 }
[[programs.tracks]]
sequence = "1000 dur [ 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1 ]"
target   = { object = "effect2", parameter = "amount", component = 1 }

# Video playing

[[programs]]
name = "video"
[programs.objects]
video  = { object = "gfx-video", args = [ { filepath = "/home/dave/Workspace/davebrent/hans-assets/output.ivf" } ] }
effect = { object = "gfx-filter" }
window = { object = "gfx-quad" }
[[programs.graphics]]
source = "video"
outlet = 0
sink   = "effect"
inlet  = 0
[[programs.graphics]]
source = "effect"
outlet = 0
sink   = "window"
inlet  = 0
[[programs.tracks]]
sequence = "2000 dur [ 9 0 0 8 0 0 9 8 ]"
target   = { object = "effect", parameter = "filter", component = 0 }
[[programs.tracks]]
sequence = "2000 dur [ 1 0 0 2 0 0 1 3 ]"
target   = { object = "effect", parameter = "amount", component = 0 }
scale    = 0.1
[[programs.tracks]]
sequence = "2000 dur [ 10 10 8 10 10 10 6 10 ]"
target   = { object = "effect", parameter = "amount", component = 1 }
scale    = 0.1

### A program showing the superformula being manipulated by an audio signal

[[programs]]
name = "superformula"
[programs.objects]
adc    = { object = "snd-in", args = [ { channel = 1 } ] }
feat   = { object = "snd-feature", args = [ { method = "centroid" } ] }
shape  = { object = "gfx-superformula" }
effect = { object = "gfx-filter" }
window = { object = "gfx-quad" }
[[programs.audio]]
source = "adc"
outlet = 0
sink   = "feat"
inlet  = 0
[[programs.graphics]]
source = "shape"
outlet = 0
sink   = "effect"
inlet  = 0
[[programs.graphics]]
source = "effect"
outlet = 0
sink   = "window"
inlet  = 0
[[programs.modulators]]
source = {object = "feat", parameter = "centroid", component = 0}
target = {object = "shape", parameter = "scale", component = 0}
scale  = 0.0001
offset = 0

# A program that outputs a noise texture

[[programs]]
name = "noise"
[programs.objects]
noise  = { object = "gfx-perlin" }
window = { object = "gfx-quad" }
[[programs.graphics]]
source = "noise"
outlet = 0
sink   = "window"
inlet  = 0

# A program that passes audio in to audio out

[[programs]]
name = "passthrough"
[programs.objects]
adc    = { object = "snd-in", args = [ { channel = 0 }, { channel = 1 } ] }
dac    = { object = "snd-out", args = [ { channel = 0 }, { channel = 1 } ] }
[[programs.audio]]
source = "adc"
outlet = 0
sink   = "dac"
inlet  = 0
[[programs.audio]]
source = "adc"
outlet = 1
sink   = "dac"
inlet  = 1

# A program that outputs a sine wave

[[programs]]
name = "sinewave"
[programs.objects]
osc    = { object = "snd-oscillator", args = [ { channels = 2 } ] }
dac    = { object = "snd-out", args = [ { channel = 0 }, { channel = 1 } ] }
[[programs.audio]]
source = "osc"
outlet = 0
sink   = "dac"
inlet  = 0
[[programs.audio]]
source = "osc"
outlet = 1
sink   = "dac"
inlet  = 1

# Sharing audio data with graphics objects

[[programs]]
name = "ringbuffers"
[programs.objects]
adc    = { object = "snd-in", args = [ { channel = 0 } ] }
ring   = { object = "snd-ringbuffer", args = [ { name = "my-ring" } ] }
dac    = { object = "snd-out", args = [ { channel = 0 } ] }
tex    = { object = "gfx-sndtex", args = [ { name = "my-ring" } ] }
window = { object = "gfx-quad" }
[[programs.audio]]
source = "adc"
outlet = 0
sink   = "ring"
inlet  = 0
[[programs.audio]]
source = "ring"
outlet = 0
sink   = "dac"
inlet  = 0
[[programs.graphics]]
source = "tex"
outlet = 0
sink   = "window"
inlet  = 0

# Using audio scopes

[[programs]]
name = "oscilloscope"
[programs.objects]
adc    = { object = "snd-in", args = [ { channel = 0 } ] }
ring   = { object = "snd-ringbuffer", args = [ { name = "my-ring" } ] }
dac    = { object = "snd-out", args = [ { channel = 0 } ] }
scope  = { object = "gfx-oscilloscope", args = [ { left = "my-ring" },
                                                 { right = "my-ring" } ] }
window = { object = "gfx-quad" }
[[programs.audio]]
source = "adc"
outlet = 0
sink   = "ring"
inlet  = 0
[[programs.audio]]
source = "ring"
outlet = 0
sink   = "dac"
inlet  = 0
[[programs.graphics]]
source = "scope"
outlet = 0
sink   = "window"

# Modulating attractors

[[programs]]
name = "attractors"
[programs.objects]
attrs  = { object = "gfx-attractors" }
window = { object = "gfx-quad" }
[[programs.graphics]]
source = "attrs"
outlet = 0
sink   = "window"
inlet  = 0
[[programs.modulators]]
source = {object = "attrs", parameter = "a", component = 0}
target = {object = "attrs", parameter = "b", component = 0}
scale  = 1
offset = 0
[[programs.modulators]]
source = {object = "attrs", parameter = "b", component = 0}
target = {object = "attrs", parameter = "a", component = 0}
scale  = 1
offset = 0

# Real-time FFT

[[programs]]
name = "fft"
[programs.objects]
adc    = { object = "snd-in", args = [ { channel = 0 } ] }
ring   = { object = "snd-ringbuffer", args = [ { name = "my-fft-ring" } ] }
fft    = { object = "snd-fft" }
ifft   = { object = "snd-ifft" }
dac    = { object = "snd-out", args = [ { channel = 0 } ] }
scope  = { object = "gfx-oscilloscope", args = [ { left = "my-fft-ring" },
                                                 { right = "my-fft-ring" } ] }
window = { object = "gfx-quad" }
[[programs.audio]]
source = "adc"
outlet = 0
sink   = "fft"
inlet  = 0
[[programs.audio]]
source = "fft"
outlet = 0
sink   = "ifft"
inlet  = 0
[[programs.audio]]
source = "fft"
outlet = 1
sink   = "ifft"
inlet  = 1
[[programs.audio]]
source = "ifft"
outlet = 0
sink   = "ring"
inlet  = 0
[[programs.audio]]
source = "ring"
outlet = 0
sink   = "dac"
inlet  = 0
[[programs.graphics]]
source = "scope"
outlet = 0
sink   = "window"
inlet  = 0
