#ifndef LIBHANS_SND_IO_GENERATED_H_
#define LIBHANS_SND_IO_GENERATED_H_

#define LIBHANS_SND_IO_ARG_CHANNEL 0x69de5123fa4a72cb
#define LIBHANS_SND_IO_ARG_BUS 0xe327f17e3594b6fd

#endif // LIBHANS_SND_IO_GENERATED_H_
