(define-module (hans compiler passes assign-graph-id)
  :use-module (hans compiler shared)
  :use-module (hans patcher)
  :export (assign-graph-id-pass))

(define (assign-graph-id-pass programs output options)
  (let ((ids 0))
    (for-each-graph (lambda (graph)
                      (set-hans-graph-id! graph ids)
                      (set! ids (+ ids 1)))
                    programs)
    output))
