find_path(LIBEFSW_INCLUDE_DIRS NAMES efsw/efsw.hpp)
find_library(LIBEFSW_LIBRARIES NAMES efsw)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LIBEFSW REQUIRED_VARS LIBEFSW_INCLUDE_DIRS LIBEFSW_LIBRARIES)

mark_as_advanced(LIBEFSW_INCLUDE_DIRS LIBEFSW_LIBRARIES)

set(LIBEFSW_FOUND FALSE)
if(LIBEFSW_LIBRARIES AND LIBEFSW_INCLUDE_DIRS)
  set(LIBEFSW_FOUND TRUE)
endif(LIBEFSW_LIBRARIES AND LIBEFSW_INCLUDE_DIRS)
